# 服务端口号
server:
  port: 10400

# 配置es服务的访问地址
spring:
  elasticsearch:
    rest:
      uris: http://192.168.200.130:9200

logging:
  level:
    tracer: trace
    com.atguigu.gmall.search.biz: trace
    org.springframework.data.elasticsearch: trace
