# 服务端口号
server:
  port: 10500

# 数据库的连接地址
spring:
  datasource:
    url: jdbc:mysql://192.168.200.130:3306/gmall_user?useSSL=false&characterEncoding=UTF8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  # 配合redis的连接信息
  redis:
    host: 192.168.200.130
    port: 6379
    password: root

# mybatis plus的相关信息
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # 日志输出的实现类
  type-aliases-package: com.atguigu.gmall.user.entity
  mapper-locations: classpath:/mapper/*.xml


