# 配置端口号
server:
  port: 11111

# 配置canal服务端的相关信息
canal:
  client:
    instances:
      example:
        host: 192.168.200.130
        port: 11111

# 配置redis的服务端的信息
spring:
  redis:
    host: 192.168.200.130
    port: 6379
    password: root

